// Code generated by mockery v2.28.1. DO NOT EDIT.

package ports

import (
	context "context"

	domain "github.com/DongnutLa/newsletter_app/internal/core/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockEventMessaging is an autogenerated mock type for the EventMessaging type
type MockEventMessaging struct {
	mock.Mock
}

// SendMessage provides a mock function with given fields: _a0, _a1
func (_m *MockEventMessaging) SendMessage(_a0 context.Context, _a1 *domain.MessageEvent) {
	_m.Called(_a0, _a1)
}

type mockConstructorTestingTNewMockEventMessaging interface {
	mock.TestingT
	Cleanup(func())
}

// NewMockEventMessaging creates a new instance of MockEventMessaging. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMockEventMessaging(t mockConstructorTestingTNewMockEventMessaging) *MockEventMessaging {
	mock := &MockEventMessaging{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
